simulator_name: "mobl_arms_index_tracking"

simulation:
  bm_model:
    cls: "MoblArmsIndex"
    kwargs:
      shoulder_variant: "none"
  task:
    cls: "Tracking"
    kwargs:
      end_effector: ["geom", "hand_2distph"]
      shoulder: ["body", "humphant"]
      episode_length_seconds: 10
  perception_modules:
    - cls: "vision.FixedEye"
      kwargs:
        resolution: [120, 80]
        channels: [3]
        buffer: 0.1
        pos: "0 0 1.2"
        quat: "0.583833 0.399104 -0.399421 -0.583368"
    - cls: "proprioception.BasicWithEndEffectorPosition"
      kwargs:
        end_effector: ["geom", "hand_2distph"]
  effort_model:
    cls: "Neural"
    kwargs:
      weight: 1e-4
  run_parameters:
    action_sample_freq: 20
    callbacks:
      - name: "freq_curriculum"
        cls: "rl.sb3.callbacks.LinearCurriculum"
        kwargs:
          start_value: 0
          end_value: 1
          start_timestep: 40_000_000
          end_timestep: 80_000_000

rl:
  algorithm: "PPO"
  policy_type: "policies.MultiInputActorCriticPolicyTanhActions"
  policy_kwargs:
    activation_fn: "torch.nn.LeakyReLU"
    net_arch: [256, 256]
    log_std_init: 0.0
    features_extractor_class: "feature_extractor.FeatureExtractor"
    normalize_images: False
  lr: 
    function: "schedule.linear_schedule"
    kwargs:
      initial_value: 5e-5
      min_value: 1e-7
      threshold: 0.8
  total_timesteps: 100_000_000
  device: "cuda"
  num_workers: 10
  nsteps: 4000
  batch_size: 500
  target_kl: 1.0
  save_freq: 5_000_000